###### 1. BUILDING CONTENT BASED RECOMMENDER SYSTEM CONSIDERING THE HYPOTHETICAL DATASET CONTAINING 8 DOCUMENTS 
######    AND 10 KEYWORDS WITH 3 POSSIBLE RATINGS (0,1,2), WITH THEIR FREQUENCIES AS 0,1 AND 2, THEREFORE, 
######    DETERMINING THE 5 MOST DISCRIMINATIVE KEYWORDS WITH THE HELP OF GINI INDEX MEASURE, AND PRINTING 
######    THE FINAL TERM-FREQUENCY DOCUMENT CORRESPONDING TO THE DISCRIMINATIVE KEYWORDS.

In [1]:
#### IMPORTING LIBRARIES
import numpy as np

In [2]:
n_docs = 8  ## NO. OF DOCUMENTS/ROWS
n_words = 10 ## NO. OF KEYWORDS/COLUMNS
n_rts = 3   ## NO. OF POSSIBLE RATINGS
k = n_docs * n_words ## NO. OF TOTAL ELEMENTS IN THE 8*10 MATRIX
n_freqs = 3   ## NO. OF FREQUENCIES/TIMES THE WORDS OCCUR IN DOCUMENTS
mat_1d = np.random.choice(n_freqs, k)
mat_2d = mat_1d.reshape(n_docs, n_words)
mat_2d

array([[2, 0, 1, 2, 1, 0, 0, 0, 0, 1],
       [2, 2, 0, 2, 1, 2, 1, 2, 0, 0],
       [0, 2, 1, 0, 0, 1, 2, 0, 2, 2],
       [0, 0, 1, 2, 2, 1, 1, 1, 2, 1],
       [1, 1, 1, 2, 0, 2, 2, 2, 1, 1],
       [1, 0, 2, 2, 1, 2, 0, 1, 2, 0],
       [0, 1, 1, 2, 0, 1, 1, 1, 0, 0],
       [2, 2, 2, 2, 0, 2, 1, 1, 2, 2]])

In [3]:
### DEFINING THE RATINGS CORRESPONDING TO EACH OF THE 8 DOCUMENTS IN THE MATRIX
mat_ratings = np.random.choice(n_rts, n_docs)
mat_ratings

array([2, 1, 1, 1, 0, 1, 1, 0])

In [4]:
gi = np.zeros(n_words)
print("1_D ARRAY FOR STORING GINI INDEX VALUES FOR 10 KEYWORDS:", gi)

1_D ARRAY FOR STORING GINI INDEX VALUES FOR 10 KEYWORDS: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
### CREATING A LOOP FOR EVERY KEYWORD DISPLAYING RATED DOCUMENTS

for j in range(n_words):   ## DEFINING THE COLUMNS/KEYWORDS
    doc_list = []  ## STORING THE INDICES OF THE jth KEYWORD IN ith DOCUMENT

   ### FINDING THE NO. OF DOCUMENTS WHERE THE KEYWORD OCCURS (NON-ZER0 FREQUENCY)
    for i in range(n_docs):
        if mat_2d[i, j] != 0:  
            doc_list.append(i)
    
  
    print(f"\nKEYWORD {j}:")
    print("\nDOCUMENTS WHICH HAVE RECEIVED RATINGS FOR THIS KEYWORD:", doc_list)
    print("\nTHE RATINGS CORRESPONDING TO THE DOCUMENTS ARE:", mat_ratings[doc_list])


    n, c = np.unique(mat_ratings[doc_list], return_counts=True)
    print("\nTHE NUMBER OF TIMES EACH RATING OCCURS ARE:", c)

    
    probability = c / sum(c)
    print("\nTHE PROBABILITIES FOR EACH RATING ARE:", probability)

   ## COMPUTING THE GINI INDEX FOR EACH KEYWORD
    gi_value = 1 - np.sum(probability**2)
    gi[j] = gi_value
    print(f"\nGINI INDEX FOR KEYWORD {j}: {gi_value}")

## PRINTING THE GINI INDICES FOR EACH KEYWORDS
print("\nGINI INDEX VALUES FOR EACH KEYWORD:")
print(gi)

## SORTING THE GINI INDICES
sorted_gi = np.sort(gi)
print("\nSORTED GINI INDEX VALUES:")
print(sorted_gi)

    


KEYWORD 0:

DOCUMENTS WHICH HAVE RECEIVED RATINGS FOR THIS KEYWORD: [0, 1, 4, 5, 7]

THE RATINGS CORRESPONDING TO THE DOCUMENTS ARE: [2 1 0 1 0]

THE NUMBER OF TIMES EACH RATING OCCURS ARE: [2 2 1]

THE PROBABILITIES FOR EACH RATING ARE: [0.4 0.4 0.2]

GINI INDEX FOR KEYWORD 0: 0.6399999999999999

KEYWORD 1:

DOCUMENTS WHICH HAVE RECEIVED RATINGS FOR THIS KEYWORD: [1, 2, 4, 6, 7]

THE RATINGS CORRESPONDING TO THE DOCUMENTS ARE: [1 1 0 1 0]

THE NUMBER OF TIMES EACH RATING OCCURS ARE: [2 3]

THE PROBABILITIES FOR EACH RATING ARE: [0.4 0.6]

GINI INDEX FOR KEYWORD 1: 0.48

KEYWORD 2:

DOCUMENTS WHICH HAVE RECEIVED RATINGS FOR THIS KEYWORD: [0, 2, 3, 4, 5, 6, 7]

THE RATINGS CORRESPONDING TO THE DOCUMENTS ARE: [2 1 1 0 1 1 0]

THE NUMBER OF TIMES EACH RATING OCCURS ARE: [2 4 1]

THE PROBABILITIES FOR EACH RATING ARE: [0.28571429 0.57142857 0.14285714]

GINI INDEX FOR KEYWORD 2: 0.5714285714285714

KEYWORD 3:

DOCUMENTS WHICH HAVE RECEIVED RATINGS FOR THIS KEYWORD: [0, 1, 3, 4, 5, 6, 7]



In [6]:
### LISTING OF THE 5 MOST DISCRIMINATIVE KEYWORDS
most_discriminative_keywords = np.argsort(gi)[:5]
print("\nMOST DISCRIMINATIVE KEYWORDS (BASED ON GINI INDEX VALUE):", most_discriminative_keywords)


MOST DISCRIMINATIVE KEYWORDS (BASED ON GINI INDEX VALUE): [4 5 6 7 1]


In [7]:
### PRINTING TH FINAL TFD CORRESPONDING TO THE DISCRIMINATIVE WORDS
final_tfd = mat_2d[:, most_discriminative_keywords]
print("THE FINAL TERM FREQUENCY DOCUMENT IS:\n", final_tfd)

THE FINAL TERM FREQUENCY DOCUMENT IS:
 [[1 0 0 0 0]
 [1 2 1 2 2]
 [0 1 2 0 2]
 [2 1 1 1 0]
 [0 2 2 2 1]
 [1 2 0 1 0]
 [0 1 1 1 1]
 [0 2 1 1 2]]


###### 2. BUILDING CONTENT BASED RECOMMENDER SYSTEM CONSIDERING THE HYPOTHETICAL DATASET CONTAINING 25 DOCUMENTS
######    AND 75 KEYWORDS WITH 4 POSSIBLE RATINGS (0,1,2,3), WITH THEIR FREQUENCIES AS 0,1,2,3, THEREFORE, DETERMINING
######    THE 10 MOST DISCRIMINATIVE KEYWORDS WITH THE HELP OF ENTROPY, AND PRINTING THE FINAL TERM-FREQUENCY DOCUMENT 
######    CORRESPONDING TO THE DISCRIMINATIVE KEYWORDS.

In [8]:
n_docs = 25  ## NO. OF DOCUMENTS/ROWS
n_words = 75 ## NO. OF KEYWORDS/COLUMNS
n_rts = 4   ## NO. OF POSSIBLE RATINGS
k = n_docs * n_words ## NO. OF TOTAL ELEMENTS IN THE 25*75 MATRIX
n_freqs = 4   ## NO. OF FREQUENCIES/TIMES THE WORDS OCCUR IN DOCUMENTS
mat_1d = np.random.choice(n_freqs, k)
mat_2d = mat_1d.reshape(n_docs, n_words)
mat_2d

array([[3, 1, 2, ..., 1, 0, 0],
       [3, 3, 1, ..., 3, 3, 0],
       [2, 1, 3, ..., 1, 2, 2],
       ...,
       [2, 1, 1, ..., 2, 0, 1],
       [1, 0, 2, ..., 2, 1, 3],
       [1, 3, 3, ..., 3, 3, 1]])

In [9]:
### DEFINING THE RATINGS CORRESPONDING TO EACH OF THE 25 DOCUMENTS IN THE MATRIX
mat_ratings = np.random.choice(n_rts, n_docs)
mat_ratings

array([0, 3, 3, 3, 2, 0, 2, 0, 3, 1, 3, 2, 2, 1, 2, 0, 0, 0, 2, 2, 2, 2,
       0, 1, 1])

In [10]:
en = np.zeros(n_words)
print("1_D ARRAY FOR STORING ENTROPY VALUES FOR 75 KEYWORDS:", en)

1_D ARRAY FOR STORING ENTROPY VALUES FOR 75 KEYWORDS: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0.]


In [11]:
for j in range(n_words):   ## DEFINING THE COLUMNS/KEYWORDS
    doc_list = []  ## STORING THE INDICES OF THE jth KEYWORD IN ith DOCUMENT

   ### FINDING THE NO. OF DOCUMENTS WHERE THE KEYWORD OCCURS (NON-ZER0 FREQUENCY)
    for i in range(n_docs):
        if mat_2d[i, j] != 0:  
            doc_list.append(i)
    
  
    print(f"\nKEYWORD {j}:")
    print("\nDOCUMENTS WHICH HAVE RECEIVED RATINGS FOR THIS KEYWORD:", doc_list)
    print("\nTHE RATINGS CORRESPONDING TO THE DOCUMENTS ARE:", mat_ratings[doc_list])


    n, c = np.unique(mat_ratings[doc_list], return_counts=True)
    print("\nTHE NUMBER OF TIMES EACH RATING OCCURS ARE:", c)

    
    probability = c / sum(c)
    print("\nTHE PROBABILITIES FOR EACH RATING ARE:", probability)

   ## COMPUTING THE ENTROPY FOR EACH KEYWORD
    entropy = -np.sum(probability * np.log(probability))
    en[j] = entropy
    print(f"\nENTROPY FOR KEYWORD {j}: {entropy}")

## PRINTING THE GINI INDICES FOR EACH KEYWORDS
print("\nENTROPY VALUES FOR EACH KEYWORD:", en)

## SORTING THE ENTROPIES
sorted_en = np.sort(en)
print("\nSORTED GINI INDEX VALUES:")
print(sorted_en)



KEYWORD 0:

DOCUMENTS WHICH HAVE RECEIVED RATINGS FOR THIS KEYWORD: [0, 1, 2, 3, 6, 8, 10, 11, 12, 13, 14, 15, 18, 19, 20, 21, 22, 23, 24]

THE RATINGS CORRESPONDING TO THE DOCUMENTS ARE: [0 3 3 3 2 3 3 2 2 1 2 0 2 2 2 2 0 1 1]

THE NUMBER OF TIMES EACH RATING OCCURS ARE: [3 3 8 5]

THE PROBABILITIES FOR EACH RATING ARE: [0.15789474 0.15789474 0.42105263 0.26315789]

ENTROPY FOR KEYWORD 0: 1.2984181566602382

KEYWORD 1:

DOCUMENTS WHICH HAVE RECEIVED RATINGS FOR THIS KEYWORD: [0, 1, 2, 3, 5, 6, 7, 9, 10, 12, 14, 15, 17, 18, 20, 21, 22, 24]

THE RATINGS CORRESPONDING TO THE DOCUMENTS ARE: [0 3 3 3 0 2 0 1 3 2 2 0 0 2 2 2 0 1]

THE NUMBER OF TIMES EACH RATING OCCURS ARE: [6 2 6 4]

THE PROBABILITIES FOR EACH RATING ARE: [0.33333333 0.11111111 0.33333333 0.22222222]

ENTROPY FOR KEYWORD 1: 1.310783678099714

KEYWORD 2:

DOCUMENTS WHICH HAVE RECEIVED RATINGS FOR THIS KEYWORD: [0, 1, 2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18, 19, 20, 21, 22, 23, 24]

THE RATINGS CORRESPONDING TO THE DOCUMEN

In [12]:
### LISTING OF THE 10 MOST DISCRIMINATIVE KEYWORDS
most_discriminative_keywords = np.argsort(en)[:10]
print("\nMOST DISCRIMINATIVE KEYWORDS (BASED ON ENTROPY VALUE):", most_discriminative_keywords)


MOST DISCRIMINATIVE KEYWORDS (BASED ON ENTROPY VALUE): [ 7 23 50 21 13 51 55 16 35 53]


In [13]:
### PRINTING TH FINAL TFD CORRESPONDING TO THE DISCRIMINATIVE WORDS
final_tfd = mat_2d[:, most_discriminative_keywords]
print("THE FINAL TERM FREQUENCY DOCUMENT IS:\n", final_tfd)

THE FINAL TERM FREQUENCY DOCUMENT IS:
 [[1 1 0 3 0 3 1 3 2 1]
 [2 0 0 3 1 0 2 2 1 3]
 [2 2 1 3 2 1 1 0 3 3]
 [0 0 0 3 3 0 0 0 1 0]
 [2 1 1 0 0 1 3 2 3 1]
 [1 0 3 2 3 0 1 3 1 0]
 [2 2 3 1 1 0 1 0 3 2]
 [3 0 3 2 2 0 2 0 0 0]
 [1 3 3 1 1 0 1 0 3 1]
 [0 0 3 1 0 1 0 1 0 0]
 [0 1 0 1 1 0 2 3 3 1]
 [1 0 0 0 2 1 0 2 2 0]
 [0 2 0 1 1 3 0 1 1 1]
 [3 1 0 0 0 1 0 3 0 0]
 [2 2 1 0 3 3 0 2 0 3]
 [2 1 2 2 1 0 3 0 3 0]
 [3 0 3 1 2 2 1 0 3 2]
 [3 0 0 3 2 2 1 0 1 2]
 [1 1 3 3 3 0 2 0 2 3]
 [2 1 2 0 3 1 0 2 1 0]
 [0 3 2 0 1 2 0 2 3 1]
 [3 1 0 0 2 2 1 1 0 0]
 [2 0 0 3 2 2 1 2 2 0]
 [0 3 0 0 1 2 0 0 0 1]
 [0 0 0 0 0 2 2 0 3 0]]
